import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedEpisode1754486236413 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const seasons = await queryRunner.query(`
        SELECT id, name FROM "season"
        `);
    if (!seasons) {
      throw new Error(
        "Seasons non trouvé. Exécutez d'abord la migration SeedSeason",
      );
    }
    const seasonMap = seasons.reduce((map, season) => {
      map[season.name] = season.id;
      return map;
    });

    const episodes = [
      { name: null, number: 6, seasonId: seasonMap['épisodes pilotes'] },
      { name: null, number: null, seasonId: seasonMap['Livre I'] },
      { name: null, number: null, seasonId: seasonMap['Livre III'] },
      { name: 'À la volette', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Ablutions', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'Agnus dei', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Always', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Ambidextrie', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Amen', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Anges et démons', number: 53, seasonId: seasonMap['Livre IV'] },
      { name: 'Anton', number: 69, seasonId: seasonMap['Livre V'] },
      {
        name: 'Arthur et la question',
        number: 13,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Arthur et les ténèbres',
        number: 41,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Arthur in love', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Arthur sensei', number: 40, seasonId: seasonMap['Livre III'] },
      { name: 'Arturi inquisitio', number: 4, seasonId: seasonMap['Livre VI'] },
      { name: 'Arturus Rex', number: 7, seasonId: seasonMap['Livre VI'] },
      {
        name: 'Au bonheur des dames',
        number: 55,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Au service secret de sa majesté',
        number: 20,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Aux yeux de tous II',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Aux yeux de tous III',
        number: 21,
        seasonId: seasonMap['Livre V'],
      },
      { name: 'Basidiomycètes', number: 31, seasonId: seasonMap['Livre I'] },
      { name: 'Centurio', number: 2, seasonId: seasonMap['Livre VI'] },
      { name: 'Chante sloubi', number: null, seasonId: seasonMap['Livre III'] },
      {
        name: 'Codes et stratégies',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Corpore sano', number: 76, seasonId: seasonMap['Livre II'] },
      { name: 'Corpore sano II', number: 82, seasonId: seasonMap['Livre IV'] },
      { name: 'Corvus corone', number: 7, seasonId: seasonMap['Livre V'] },
      {
        name: 'Cryda de Tintagel',
        number: 18,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Cuisine et dépendances',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Dagonet et le cadastre',
        number: 14,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'De retour de Judée',
        number: 27,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Décibels nocturnes',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Dies irae', number: 9, seasonId: seasonMap['Livre VI'] },
      { name: 'Dîner dansant', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Domi nostrae', number: 33, seasonId: seasonMap['Livre V'] },
      { name: 'Duel II', number: null, seasonId: seasonMap['Livre IV'] },
      { name: 'Dux bellorum', number: 5, seasonId: seasonMap['Livre VI'] },
      {
        name: 'En forme de graal',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Enluminures', number: 51, seasonId: seasonMap['Livre I'] },
      {
        name: 'Excalibur et le destin',
        number: 52,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Executor', number: 28, seasonId: seasonMap['Livre V'] },
      {
        name: "Feue l'âne de Guethenoc",
        number: 62,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Feue la poule de Guethenoc',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Feue la vache de Roparzh',
        number: 69,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Fluctuat nec mergitur',
        number: 80,
        seasonId: seasonMap['Livre IV'],
      },
      { name: 'Goustan le cruel', number: 63, seasonId: seasonMap['Livre I'] },
      {
        name: 'Guenievre et les oiseaux',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Haunted', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Heat', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Hollow man', number: 98, seasonId: seasonMap['Livre III'] },
      { name: 'Hurlements', number: 11, seasonId: seasonMap['Livre V'] },
      { name: 'Immaculé Karadoc', number: 20, seasonId: seasonMap['Livre II'] },
      { name: 'Jizô', number: 38, seasonId: seasonMap['Livre V'] },
      { name: "L'absent", number: null, seasonId: seasonMap['Livre II'] },
      { name: "L'absolution", number: 19, seasonId: seasonMap['Livre II'] },
      { name: "L'abstinent", number: 44, seasonId: seasonMap['Livre III'] },
      { name: "L'alliance", number: 61, seasonId: seasonMap['Livre II'] },
      { name: "L'ambition", number: 74, seasonId: seasonMap['Livre II'] },
      { name: "L'ancien temps", number: 33, seasonId: seasonMap['Livre II'] },
      { name: "L'approbation", number: 83, seasonId: seasonMap['Livre IV'] },
      {
        name: "L'arche de transport",
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: "L'art de la table",
        number: 33,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: "L'assassin de kaamelott",
        number: 29,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: "L'assemblée des rois",
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: "L'assemblée des rois II",
        number: 90,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: "L'avènement du sanguinaire",
        number: null,
        seasonId: seasonMap['Livre V'],
      },
      {
        name: "L'aveu de Bohort",
        number: 3,
        seasonId: seasonMap['Livre III'],
      },
      { name: "L'échange", number: null, seasonId: seasonMap['Livre IV'] },
      {
        name: "L'échelle de Perceval",
        number: null,
        seasonId: seasonMap['Livre IV'],
      },
      { name: "L'élu", number: null, seasonId: seasonMap['Livre V'] },
      { name: "L'empressée", number: null, seasonId: seasonMap['Livre III'] },
      {
        name: "L'enlèvement de Guenièvre",
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: "L'entente cordiale",
        number: 82,
        seasonId: seasonMap['Livre IV'],
      },
      { name: "L'épée des rois", number: 6, seasonId: seasonMap['Livre V'] },
      { name: "L'escorte", number: null, seasonId: seasonMap['Livre I'] },
      { name: "L'escorte II", number: 37, seasonId: seasonMap['Livre II'] },
      { name: "L'espion", number: 91, seasonId: seasonMap['Livre III'] },
      { name: "L'étudiant", number: 88, seasonId: seasonMap['Livre III'] },
      {
        name: "L'expurgation de merlin",
        number: 79,
        seasonId: seasonMap['Livre I'],
      },
      { name: "L'habitué", number: 66, seasonId: seasonMap['Livre IV'] },
      { name: "L'imposteur", number: null, seasonId: seasonMap['Livre I'] },
      { name: "L'inspiration", number: null, seasonId: seasonMap['Livre IV'] },
      { name: "L'interprète", number: 24, seasonId: seasonMap['Livre I'] },
      { name: "L'invincible", number: null, seasonId: seasonMap['Livre II'] },
      { name: "L'ivresse", number: 31, seasonId: seasonMap['Livre II'] },
      { name: "L'oubli", number: null, seasonId: seasonMap['Livre II'] },
      { name: 'La baliste', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'La baliste', number: null, seasonId: seasonMap['Livre IV'] },
      { name: 'La barraka', number: 28, seasonId: seasonMap['Livre III'] },
      {
        name: "La blessure d'Yvain",
        number: 81,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'La blessure mortelle',
        number: 85,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'La botte secrète', number: 28, seasonId: seasonMap['Livre I'] },
      {
        name: 'La botte secrète II',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'La cassette', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'La cassette II', number: 2, seasonId: seasonMap['Livre III'] },
      { name: 'La chambre', number: 3, seasonId: seasonMap['Livre II'] },
      {
        name: 'La chambre de la reine',
        number: 26,
        seasonId: seasonMap['Livre IV'],
      },
      { name: 'La chevalerie', number: 86, seasonId: seasonMap['Livre III'] },
      { name: 'La clandestine', number: null, seasonId: seasonMap['Livre IV'] },
      {
        name: 'La coccinelle de madenn',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'La conspiratrice', number: 41, seasonId: seasonMap['Livre V'] },
      {
        name: "La corne d'abondance",
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'La dame et le lac',
        number: null,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'La délégation maure',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'La démission', number: 9, seasonId: seasonMap['Livre V'] },
      { name: 'La dent de requin', number: 20, seasonId: seasonMap['Livre I'] },
      { name: 'La dispute', number: 99, seasonId: seasonMap['Livre III'] },
      { name: 'La dispute II', number: 100, seasonId: seasonMap['Livre III'] },
      {
        name: "La fête de l'hiver",
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'La fête du printemps',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'La foi bretonne',
        number: null,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'La fureur du dragon',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'La garde royale', number: 30, seasonId: seasonMap['Livre II'] },
      {
        name: 'La grande bataille',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'La joute ancillaire',
        number: 37,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'La jupe de Calogrenant',
        number: 59,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'La kleptomane', number: null, seasonId: seasonMap['Livre I'] },
      {
        name: 'La menace fantôme',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'La mission', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'La parade', number: 21, seasonId: seasonMap['Livre IV'] },
      { name: "La pâte d'amande", number: 25, seasonId: seasonMap['Livre I'] },
      { name: 'La poétique', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'La poétique II', number: null, seasonId: seasonMap['Livre IV'] },
      {
        name: 'La potion de fécondité',
        number: 23,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'La potion de fécondité II',
        number: 67,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'La promesse', number: 22, seasonId: seasonMap['Livre V'] },
      {
        name: 'La quête des deux renards',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'La queue du scorpion',
        number: 22,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'La quinte juste', number: 55, seasonId: seasonMap['Livre II'] },
      {
        name: 'La réaffectation',
        number: null,
        seasonId: seasonMap['Livre IV'],
      },
      { name: 'La relève', number: null, seasonId: seasonMap['Livre IV'] },
      { name: 'La rémanence', number: 51, seasonId: seasonMap['Livre IV'] },
      { name: 'La rencontre', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'La réponse', number: 49, seasonId: seasonMap['Livre IV'] },
      { name: 'La restriction', number: null, seasonId: seasonMap['Livre II'] },
      {
        name: 'La restriction II',
        number: 72,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'La retraite', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'La révolte', number: 23, seasonId: seasonMap['Livre II'] },
      { name: 'La révolte III', number: 31, seasonId: seasonMap['Livre IV'] },
      { name: 'La révoquée', number: 28, seasonId: seasonMap['Livre IV'] },
      {
        name: 'La roche et le fer',
        number: 12,
        seasonId: seasonMap['Livre V'],
      },
      {
        name: 'La romance de Lancelot',
        number: 37,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'La ronde', number: 34, seasonId: seasonMap['Livre II'] },
      { name: 'La sorcière', number: 5, seasonId: seasonMap['Livre V'] },
      { name: 'La supplique', number: 30, seasonId: seasonMap['Livre V'] },
      {
        name: 'La table de Breccan',
        number: 3,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'La tarte aux fraises',
        number: 4,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'La tarte aux myrtilles',
        number: 2,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'La taxe militaire', number: 21, seasonId: seasonMap['Livre I'] },
      { name: 'La veillée', number: 87, seasonId: seasonMap['Livre III'] },
      {
        name: "La visite d'Ygerne",
        number: 59,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'La vraie nature du graal',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Lacrimosa', number: 95, seasonId: seasonMap['Livre I'] },
      { name: 'Lacrimosa', number: 8, seasonId: seasonMap['Livre VI'] },
      {
        name: 'Le banquet des chefs',
        number: 16,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Le cadeau', number: 46, seasonId: seasonMap['Livre II'] },
      { name: 'Le cas Yvain', number: 39, seasonId: seasonMap['Livre I'] },
      {
        name: 'Le chaudron rutilant',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Le chevalier errant',
        number: 1,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Le chevalier femme',
        number: 6,
        seasonId: seasonMap['épisodes pilotes'],
      },
      {
        name: 'Le choix de Gauvain',
        number: 78,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Le code de chevalerie',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Le complot', number: null, seasonId: seasonMap['Livre II'] },
      { name: "Le coup d'épée", number: null, seasonId: seasonMap['Livre I'] },
      {
        name: 'Le culte secret',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Le dernier empereur',
        number: 56,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Le dernier jour', number: 24, seasonId: seasonMap['Livre V'] },
      { name: 'Le dernier recours', number: 3, seasonId: seasonMap['Livre V'] },
      { name: 'Le déserteur', number: 7, seasonId: seasonMap['Livre III'] },
      {
        name: 'Le désordre et la nuit',
        number: 99,
        seasonId: seasonMap['Livre IV'],
      },
      { name: 'Le destitué', number: 42, seasonId: seasonMap['Livre V'] },
      {
        name: 'Le dialogue de paix',
        number: 3,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Le dialogue de paix II',
        number: 42,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Le discobole', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Le donneur', number: 60, seasonId: seasonMap['Livre II'] },
      {
        name: 'Le dragon des tunnels',
        number: 86,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Le duel', number: 1, seasonId: seasonMap['épisodes pilotes'] },
      { name: 'Le fléau de dieu', number: 5, seasonId: seasonMap['Livre I'] },
      {
        name: 'Le fléau de dieu II',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Le fléau de dieu II',
        number: 17,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Le forfait', number: 23, seasonId: seasonMap['Livre V'] },
      {
        name: 'Le garçon qui criait au loup',
        number: null,
        seasonId: seasonMap['Livre V'],
      },
      { name: 'Le grand départ', number: 39, seasonId: seasonMap['Livre IV'] },
      { name: 'Le guet', number: 40, seasonId: seasonMap['Livre II'] },
      {
        name: 'Le jeu de la guerre',
        number: 63,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Le jeu du caillou',
        number: 60,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: "Le jour d'Alexandre",
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Le jurisconsulte', number: 27, seasonId: seasonMap['Livre V'] },
      { name: 'Le labyrinthe', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Le larcin', number: 38, seasonId: seasonMap['Livre II'] },
      {
        name: 'Le législateur',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Le magnanime', number: null, seasonId: seasonMap['Livre III'] },
      { name: "Le maître d'armes", number: 9, seasonId: seasonMap['Livre I'] },
      { name: 'Le mangonneau', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'Le médiateur', number: 96, seasonId: seasonMap['Livre III'] },
      {
        name: 'Le message codé',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: "Le monde d'arthur",
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Le oud II', number: 75, seasonId: seasonMap['Livre IV'] },
      { name: 'Le pain', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Le paladin', number: 70, seasonId: seasonMap['Livre IV'] },
      {
        name: 'Le passage secret',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Le pédagogue', number: 71, seasonId: seasonMap['Livre II'] },
      { name: 'Le périple', number: 8, seasonId: seasonMap['Livre V'] },
      { name: 'Le petit poucet', number: 47, seasonId: seasonMap['Livre III'] },
      { name: 'Le poème', number: null, seasonId: seasonMap['Livre II'] },
      {
        name: 'Le porte bonheur',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Le portrait', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Le privilégié', number: 12, seasonId: seasonMap['Livre IV'] },
      {
        name: 'Le problème du chou',
        number: 70,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Le prodige du fakir',
        number: 60,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Le professionnel',
        number: 23,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Le rapport', number: 32, seasonId: seasonMap['Livre IV'] },
      {
        name: 'Le rassemblement du corbeau',
        number: 4,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Le rassemblement du corbeau II',
        number: 38,
        seasonId: seasonMap['Livre IV'],
      },
      { name: 'Le rebelle', number: 85, seasonId: seasonMap['Livre II'] },
      { name: 'Le reclassement', number: 14, seasonId: seasonMap['Livre II'] },
      { name: 'Le refuge', number: 55, seasonId: seasonMap['Livre IV'] },
      {
        name: 'Le renfort magique',
        number: 4,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Le renoncement II',
        number: null,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Le répurgateur',
        number: 9,
        seasonId: seasonMap['épisodes pilotes'],
      },
      {
        name: 'Le retour de judée',
        number: 27,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Le retour du roi', number: 49, seasonId: seasonMap['Livre V'] },
      {
        name: "Le rêve d'Ygerne",
        number: 64,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Le royaume sans tête',
        number: 5,
        seasonId: seasonMap['Livre V'],
      },
      { name: 'Le sacrifice', number: 25, seasonId: seasonMap['Livre I'] },
      {
        name: 'Le sanglier de cornouailles',
        number: null,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Le sauvetage', number: 98, seasonId: seasonMap['Livre IV'] },
      {
        name: "Le secret d'Arthur",
        number: 62,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Le secret de Lancelot',
        number: 53,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Le signe', number: 17, seasonId: seasonMap['Livre I'] },
      { name: 'Le sixième sens', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Le sort perdu', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Le terroriste', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Le tourment', number: 98, seasonId: seasonMap['Livre I'] },
      { name: 'Le tourment II', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Le tourment III', number: 69, seasonId: seasonMap['Livre III'] },
      { name: 'Le traitre', number: null, seasonId: seasonMap['Livre IV'] },
      { name: 'Le trouble', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'Le vice de forme', number: 91, seasonId: seasonMap['Livre IV'] },
      { name: 'Legenda', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'Les affranchis', number: 38, seasonId: seasonMap['Livre III'] },
      { name: 'Les alchimistes', number: 2, seasonId: seasonMap['Livre II'] },
      { name: 'Les aquitains', number: 15, seasonId: seasonMap['Livre V'] },
      {
        name: 'Les biens nommés',
        number: null,
        seasonId: seasonMap['Livre IV'],
      },
      { name: 'Les bonnes', number: 30, seasonId: seasonMap['Livre IV'] },
      { name: 'Les chaperons', number: null, seasonId: seasonMap['Livre IV'] },
      {
        name: 'Les cheveux noirs',
        number: 46,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Les chiens de guerre',
        number: 49,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Les classes de Bohort',
        number: 14,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Les clous de la sainte croix',
        number: 39,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Les dauphins', number: 13, seasonId: seasonMap['Livre V'] },
      {
        name: 'Les défis de Merlin',
        number: 15,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Les défis de Merlin II',
        number: 96,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Les embusqués', number: 35, seasonId: seasonMap['Livre V'] },
      { name: 'Les envahisseurs', number: 44, seasonId: seasonMap['Livre IV'] },
      { name: 'Les esclaves', number: 88, seasonId: seasonMap['Livre II'] },
      { name: 'Les exilés', number: 17, seasonId: seasonMap['Livre V'] },
      { name: 'Les exploités', number: null, seasonId: seasonMap['Livre II'] },
      {
        name: 'Les exploités II',
        number: null,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Les félicitations',
        number: 86,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Les fesses de Guenièvre',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Les festivités', number: null, seasonId: seasonMap['Livre II'] },
      {
        name: "Les fruits d'hiver",
        number: 16,
        seasonId: seasonMap['Livre V'],
      },
      {
        name: 'Les liaisons dangereuses',
        number: 15,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Les mauvaises graines',
        number: 29,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Les misanthropes', number: 21, seasonId: seasonMap['Livre II'] },
      {
        name: 'Les neiges éternelles',
        number: 66,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Les nocturnales', number: 19, seasonId: seasonMap['Livre V'] },
      { name: 'Les nouveaux clans', number: 4, seasonId: seasonMap['Livre V'] },
      {
        name: 'Les nouveaux frères',
        number: 50,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'Les novices', number: 34, seasonId: seasonMap['Livre IV'] },
      { name: 'Les paris II', number: 53, seasonId: seasonMap['Livre III'] },
      { name: 'Les pionniers', number: 40, seasonId: seasonMap['Livre V'] },
      { name: 'Les pisteurs', number: null, seasonId: seasonMap['Livre IV'] },
      {
        name: 'Les plaques de dissimulation',
        number: 90,
        seasonId: seasonMap['Livre IV'],
      },
      { name: 'Les recruteurs', number: 10, seasonId: seasonMap['Livre V'] },
      { name: 'Les repentant', number: 1, seasonId: seasonMap['Livre V'] },
      { name: 'Les repentants', number: 1, seasonId: seasonMap['Livre V'] },
      { name: 'Les rivales', number: null, seasonId: seasonMap['Livre V'] },
      { name: 'Les suppléants', number: 24, seasonId: seasonMap['Livre III'] },
      { name: 'Les tourelles', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'Les transhumants', number: 37, seasonId: seasonMap['Livre V'] },
      { name: 'Les tuteurs', number: 16, seasonId: seasonMap['Livre II'] },
      { name: 'Les voeux', number: 45, seasonId: seasonMap['Livre II'] },
      {
        name: 'Les volontaires II',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Loth et le graal', number: 67, seasonId: seasonMap['Livre IV'] },
      { name: 'Mater dixit', number: 69, seasonId: seasonMap['Livre II'] },
      {
        name: "Merlin l'archaïque",
        number: 56,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Miles ignotus', number: 1, seasonId: seasonMap['Livre VI'] },
      { name: 'Mission', number: 65, seasonId: seasonMap['Livre III'] },
      { name: 'Monogame', number: 14, seasonId: seasonMap['Livre I'] },
      { name: 'Morituri', number: null, seasonId: seasonMap['Livre III'] },
      {
        name: 'Neiges éternelles',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Nuptiae', number: 6, seasonId: seasonMap['Livre VI'] },
      { name: "O'brother", number: 41, seasonId: seasonMap['Livre II'] },
      {
        name: 'Patience dans la plaine',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Perceval de sinope',
        number: null,
        seasonId: seasonMap['Livre V'],
      },
      {
        name: 'Perceval et le contre-sirop',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Perceval fait raitournelle',
        number: null,
        seasonId: seasonMap['Livre IV'],
      },
      { name: 'Plus près de toi', number: 22, seasonId: seasonMap['Livre II'] },
      {
        name: 'Plusieurs épisodes de la saison V',
        number: null,
        seasonId: seasonMap['Livre V'],
      },
      { name: 'Poltergeist', number: null, seasonId: seasonMap['Livre III'] },
      { name: 'Polymorphie', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Praeceptores', number: 3, seasonId: seasonMap['Livre VI'] },
      {
        name: 'Promotion de la série',
        number: null,
        seasonId: seasonMap['décembre 2004'],
      },
      {
        name: 'Promotion de la série',
        number: null,
        seasonId: seasonMap['janvier 2005'],
      },
      {
        name: "Raison d'argent II",
        number: 88,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: 'Raisons et sentiments',
        number: 3,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Réplique souvent répétée',
        number: null,
        seasonId: seasonMap['Livre V'],
      },
      {
        name: 'Saponides et détergents',
        number: 74,
        seasonId: seasonMap['Livre III'],
      },
      {
        name: "Séfriane d'aquitaine",
        number: 16,
        seasonId: seasonMap['Livre III'],
      },
      { name: 'Seigneur Caïus', number: 22, seasonId: seasonMap['Livre IV'] },
      {
        name: 'Séli et les rongeurs',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Sept cent quarante-quatre',
        number: null,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Silbury hill', number: 5, seasonId: seasonMap['Livre II'] },
      { name: 'Sous les verrous', number: 24, seasonId: seasonMap['Livre II'] },
      { name: 'Spangenhelm', number: 1, seasonId: seasonMap['Livre II'] },
      { name: 'Spiritueux', number: 33, seasonId: seasonMap['Livre II'] },
      { name: 'Stargate', number: 93, seasonId: seasonMap['Livre II'] },
      {
        name: 'Tel un chevalier',
        number: null,
        seasonId: seasonMap['Livre I'],
      },
      { name: 'The game', number: null, seasonId: seasonMap['Livre II'] },
      {
        name: 'Tous les matins du monde',
        number: 2,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Tous les matins du monde II',
        number: 2,
        seasonId: seasonMap['Livre IV'],
      },
      {
        name: 'Trois cent soixante degrés',
        number: 97,
        seasonId: seasonMap['Livre II'],
      },
      {
        name: 'Un bruit dans la nuit',
        number: 61,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Un roi à la taverne',
        number: 21,
        seasonId: seasonMap['Livre I'],
      },
      {
        name: 'Un roi à la taverne II',
        number: 26,
        seasonId: seasonMap['Livre II'],
      },
      { name: 'Unagi', number: null, seasonId: seasonMap['Livre I'] },
      { name: 'Unagi II', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Unagi IV', number: null, seasonId: seasonMap['Livre IV'] },
      { name: 'Unagi V', number: 39, seasonId: seasonMap['Livre V'] },
      { name: 'Vae soli !', number: 14, seasonId: seasonMap['Livre V'] },
      { name: 'Vox populi II', number: null, seasonId: seasonMap['Livre II'] },
      { name: 'Vox populi III', number: 58, seasonId: seasonMap['Livre IV'] },
      { name: 'Witness', number: 82, seasonId: seasonMap['Livre III'] },
    ];

    for (const episode of episodes) {
      await queryRunner.query(
        `
        INSERT INTO "episode" ("name", "number", "seasonId") VALUES 
        ($1, $2, $3)
        ON CONFLICT (
          "seasonId",
          COALESCE("number", -1),
          "name"
        ) DO NOTHING
      `,
        [episode.name, episode.number, episode.seasonId],
      );
    }

    console.log('✅ episode insérés');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM "episode" 
      WHERE "seasonId" IN (
        SELECT s.id 
        FROM "season" s 
        INNER JOIN "show" sh ON s."showId" = sh.id 
        WHERE sh.name = 'kaamelott'
      )
    `);

    console.log('🗑️ episode supprimés');
  }
}
