import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedCharacters1754486166181 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO "character" ("name") VALUES
      ('Alzagar'),
      ('Angharad'),
      ('Anna de Tintagel'),
      ('Appius Manilius'),
      ('Arthur'),
      ('Attila'),
      ('Belt'),
      ('Bohort'),
      ('Breccan l''artisan irlandais'),
      ('Caius Camillus'),
      ('Calogrenant'),
      ('César'),
      ('Cryda de Tintagel'),
      ('Dagonet'),
      ('Demetra'),
      ('Drusilla'),
      ('Edern le Chevalier Femme'),
      ('Élias de Kelliwic''h'),
      ('Faerbach'),
      ('Galessin Duc d''Orcanie'),
      ('Gauvain'),
      ('Goustan'),
      ('Grüdü'),
      ('Guenièvre'),
      ('Guethenoc'),
      ('Hervé de Rinel'),
      ('Horsa'),
      ('Kadoc'),
      ('Karadoc'),
      ('L''interprète burgonde'),
      ('La Dame du Lac'),
      ('La Duchesse d''Aquitaine'),
      ('Lancelot'),
      ('Le Duc d''Aquitaine'),
      ('Le Jurisconsulte'),
      ('Le maître d''armes'),
      ('Le Répurgateur'),
      ('Le roi burgonde'),
      ('Le Seigneur Jacca'),
      ('Le tavernier'),
      ('Le tricheur'),
      ('Léodagan'),
      ('Les Jumelles du pêcheur'),
      ('Loth'),
      ('Lucius Sillius Sallustius'),
      ('Manius Macrinus Firmus'),
      ('Méléagant'),
      ('Merlin'),
      ('Mevanwi'),
      ('Nessa'),
      ('Perceval'),
      ('Père Blaise'),
      ('Publius Servius Capito'),
      ('Quarto'),
      ('Roparzh'),
      ('Séfriane d''Aquitaine'),
      ('Séli'),
      ('Spurius Cordius Frontinius'),
      ('Titus Nipius Glaucia'),
      ('Urgan'),
      ('Venec'),
      ('Vérinus'),
      ('Ygerne'),
      ('Yvain')
      ON CONFLICT DO NOTHING
    `);

    console.log('✅ Personnages insérés avec succès');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM "character" WHERE "name" IN (
        'Alzagar',
        'Angharad',
        'Anna de Tintagel',
        'Appius Manilius',
        'Arthur',
        'Attila',
        'Belt',
        'Bohort',
        'Breccan l''artisan irlandais',
        'Caius Camillus',
        'Calogrenant',
        'César',
        'Cryda de Tintagel',
        'Dagonet',
        'Demetra',
        'Drusilla',
        'Edern le Chevalier Femme',
        'Élias de Kelliwic''h',
        'Faerbach',
        'Galessin Duc d''Orcanie',
        'Gauvain',
        'Goustan',
        'Grüdü',
        'Guenièvre',
        'Guethenoc',
        'Hervé de Rinel',
        'Horsa',
        'Kadoc',
        'Karadoc',
        'L''interprète burgonde',
        'La Dame du Lac',
        'La Duchesse d''Aquitaine',
        'Lancelot',
        'Le Duc d''Aquitaine',
        'Le Jurisconsulte',
        'Le maître d''armes',
        'Le Répurgateur',
        'Le roi burgonde',
        'Le Seigneur Jacca',
        'Le tavernier',
        'Le tricheur',
        'Léodagan',
        'Les Jumelles du pêcheur',
        'Loth',
        'Lucius Sillius Sallustius',
        'Manius Macrinus Firmus',
        'Méléagant',
        'Merlin',
        'Mevanwi',
        'Nessa',
        'Perceval',
        'Père Blaise',
        'Publius Servius Capito',
        'Quarto',
        'Roparzh',
        'Séfriane d''Aquitaine',
        'Séli',
        'Spurius Cordius Frontinius',
        'Titus Nipius Glaucia',
        'Urgan',
        'Venec',
        'Vérinus',
        'Ygerne',
        'Yvain'
      )
    `);

    console.log('🗑️ Personnages supprimés');
  }
}
