import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedEpisode1754486236413 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const seasons = await queryRunner.query(`
        SELECT id, name FROM "season"
        `);

    if (!seasons) {
      throw new Error(
        "Seasons non trouvé. Exécutez d'abord la migration SeedSeason",
      );
    }

    const seasonMap = seasons.reduce((map, season) => {
      map[season.name] = season.id;
      return map;
    }, {});

    await queryRunner.query(`
      INSERT INTO "episode" ("name", "number", "seasonId") VALUES 
      (NULL, 6, ${seasonMap['épisodes pilotes']}),
      (NULL, NULL, ${seasonMap['Livre I']}),
      (NULL, NULL, ${seasonMap['Livre III']}),
      ('À la volette', NULL, ${seasonMap['Livre I']}),
      ('Ablutions', NULL, ${seasonMap['Livre III']}),
      ('Agnus dei', NULL, ${seasonMap['Livre I']}),
      ('Always', NULL, ${seasonMap['Livre II']}),
      ('Ambidextrie', NULL, ${seasonMap['Livre I']}),
      ('Amen', NULL, ${seasonMap['Livre II']}),
      ('Anges et démons', 53, ${seasonMap['Livre IV']}),
      ('Anton', 69, ${seasonMap['Livre V']}),
      ('Arthur et la question', 13, ${seasonMap['Livre I']}),
      ('Arthur et les ténèbres', 41, ${seasonMap['Livre I']}),
      ('Arthur in love', NULL, ${seasonMap['Livre II']}),
      ('Arthur sensei', 40, ${seasonMap['Livre III']}),
      ('Arturi inquisitio', 4, ${seasonMap['Livre VI']}),
      ('Arturus Rex', 7, ${seasonMap['Livre VI']}),
      ('Au bonheur des dames', 55, ${seasonMap['Livre III']}),
      ('Au service secret de sa majesté', 20, ${seasonMap['Livre IV']}),
      ('Aux yeux de tous II', NULL, ${seasonMap['Livre III']}),
      ('Aux yeux de tous III', 21, ${seasonMap['Livre V']}),
      ('Basidiomycètes', 31, ${seasonMap['Livre I']}),
      ('Centurio', 2, ${seasonMap['Livre VI']}),
      ('Chante sloubi', NULL, ${seasonMap['Livre III']}),
      ('Codes et stratégies', NULL, ${seasonMap['Livre I']}),
      ('Corpore sano', 76, ${seasonMap['Livre II']}),
      ('Corpore sano II', 82, ${seasonMap['Livre IV']}),
      ('Corvus corone', 7, ${seasonMap['Livre V']}),
      ('Cryda de Tintagel', 18, ${seasonMap['Livre III']}),
      ('Cuisine et dépendances', NULL, ${seasonMap['Livre III']}),
      ('Dagonet et le cadastre', 14, ${seasonMap['Livre IV']}),
      ('De retour de Judée', 27, ${seasonMap['Livre I']}),
      ('Décibels nocturnes', NULL, ${seasonMap['Livre I']}),
      ('Dies irae', 9, ${seasonMap['Livre VI']}),
      ('Dîner dansant', NULL, ${seasonMap['Livre I']}),
      ('Domi nostrae', 33, ${seasonMap['Livre V']}),
      ('Duel II', NULL, ${seasonMap['Livre IV']}),
      ('Dux bellorum', 5, ${seasonMap['Livre VI']}),
      ('En forme de graal', NULL, ${seasonMap['Livre I']}),
      ('Enluminures', 51, ${seasonMap['Livre I']}),
      ('Excalibur et le destin', 52, ${seasonMap['Livre II']}),
      ('Executor', 28, ${seasonMap['Livre V']}),
      ('Feue l''âne de Guethenoc', 62, ${seasonMap['Livre I']}),
      ('Feue la poule de Guethenoc', NULL, ${seasonMap['Livre III']}),
      ('Feue la vache de Roparzh', 69, ${seasonMap['Livre II']}),
      ('Fluctuat nec mergitur', 80, ${seasonMap['Livre IV']}),
      ('Goustan le cruel', 63, ${seasonMap['Livre I']}),
      ('Guenievre et les oiseaux', NULL, ${seasonMap['Livre I']}),
      ('Haunted', NULL, ${seasonMap['Livre I']}),
      ('Heat', NULL, ${seasonMap['Livre I']}),
      ('Hollow man', 98, ${seasonMap['Livre III']}),
      ('Hurlements', 11, ${seasonMap['Livre V']}),
      ('Immaculé Karadoc', 20, ${seasonMap['Livre II']}),
      ('Jizô', 38, ${seasonMap['Livre V']}),
      ('L''absent', NULL, ${seasonMap['Livre II']}),
      ('L''absolution', 19, ${seasonMap['Livre II']}),
      ('L''abstinent', 44, ${seasonMap['Livre III']}),
      ('L''alliance', 61, ${seasonMap['Livre II']}),
      ('L''ambition', 74, ${seasonMap['Livre II']}),
      ('L''ancien temps', 33, ${seasonMap['Livre II']}),
      ('L''approbation', 83, ${seasonMap['Livre IV']}),
      ('L''arche de transport', NULL, ${seasonMap['Livre III']}),
      ('L''art de la table', 33, ${seasonMap['Livre IV']}),
      ('L''assassin de kaamelott', 29, ${seasonMap['Livre I']}),
      ('L''assemblée des rois', NULL, ${seasonMap['Livre III']}),
      ('L''assemblée des rois II', 90, ${seasonMap['Livre III']}),
      ('L''avènement du sanguinaire', NULL, ${seasonMap['Livre V']}),
      ('L''aveu de Bohort', 3, ${seasonMap['Livre III']}),
      ('L''échange', NULL, ${seasonMap['Livre IV']}),
      ('L''échelle de Perceval', NULL, ${seasonMap['Livre IV']}),
      ('L''élu', NULL, ${seasonMap['Livre V']}),
      ('L''empressée', NULL, ${seasonMap['Livre III']}),
      ('L''enlèvement de Guenièvre', NULL, ${seasonMap['Livre II']}),
      ('L''entente cordiale', 82, ${seasonMap['Livre IV']}),
      ('L''épée des rois', 6, ${seasonMap['Livre V']}),
      ('L''escorte', NULL, ${seasonMap['Livre I']}),
      ('L''escorte II', 37, ${seasonMap['Livre II']}),
      ('L''espion', 91, ${seasonMap['Livre III']}),
      ('L''étudiant', 88, ${seasonMap['Livre III']}),
      ('L''expurgation de merlin', 79, ${seasonMap['Livre I']}),
      ('L''habitué', 66, ${seasonMap['Livre IV']}),
      ('L''imposteur', NULL, ${seasonMap['Livre I']}),
      ('L''inspiration', NULL, ${seasonMap['Livre IV']}),
      ('L''interprète', 24, ${seasonMap['Livre I']}),
      ('L''invincible', NULL, ${seasonMap['Livre II']}),
      ('L''ivresse', 31, ${seasonMap['Livre II']}),
      ('L''oubli', NULL, ${seasonMap['Livre II']}),
      ('La baliste', NULL, ${seasonMap['Livre III']}),
      ('La baliste', NULL, ${seasonMap['Livre IV']}),
      ('La barraka', 28, ${seasonMap['Livre III']}),
      ('La blessure d''Yvain', 81, ${seasonMap['Livre IV']}),
      ('La blessure mortelle', 85, ${seasonMap['Livre I']}),
      ('La botte secrète', 28, ${seasonMap['Livre I']}),
      ('La botte secrète II', NULL, ${seasonMap['Livre II']}),
      ('La cassette', NULL, ${seasonMap['Livre II']}),
      ('La cassette II', 2, ${seasonMap['Livre III']}),
      ('La chambre', 3, ${seasonMap['Livre II']}),
      ('La chambre de la reine', 26, ${seasonMap['Livre IV']}),
      ('La chevalerie', 86, ${seasonMap['Livre III']}),
      ('La clandestine', NULL, ${seasonMap['Livre IV']}),
      ('La coccinelle de madenn', NULL, ${seasonMap['Livre I']}),
      ('La conspiratrice', 41, ${seasonMap['Livre V']}),
      ('La corne d''abondance', NULL, ${seasonMap['Livre III']}),
      ('La dame et le lac', NULL, ${seasonMap['Livre IV']}),
      ('La délégation maure', NULL, ${seasonMap['Livre II']}),
      ('La démission', 9, ${seasonMap['Livre V']}),
      ('La dent de requin', 20, ${seasonMap['Livre I']}),
      ('La dispute', 99, ${seasonMap['Livre III']}),
      ('La dispute II', 100, ${seasonMap['Livre III']}),
      ('La fête de l''hiver', NULL, ${seasonMap['Livre I']}),
      ('La fête du printemps', NULL, ${seasonMap['Livre II']}),
      ('La foi bretonne', NULL, ${seasonMap['Livre IV']}),
      ('La fureur du dragon', NULL, ${seasonMap['Livre I']}),
      ('La garde royale', 30, ${seasonMap['Livre II']}),
      ('La grande bataille', NULL, ${seasonMap['Livre III']}),
      ('La joute ancillaire', 37, ${seasonMap['Livre II']}),
      ('La jupe de Calogrenant', 59, ${seasonMap['Livre I']}),
      ('La kleptomane', NULL, ${seasonMap['Livre I']}),
      ('La menace fantôme', NULL, ${seasonMap['Livre III']}),
      ('La mission', NULL, ${seasonMap['Livre III']}),
      ('La parade', 21, ${seasonMap['Livre IV']}),
      ('La pâte d''amande', 25, ${seasonMap['Livre I']}),
      ('La poétique', NULL, ${seasonMap['Livre III']}),
      ('La poétique II', NULL, ${seasonMap['Livre IV']}),
      ('La potion de fécondité', 23, ${seasonMap['Livre I']}),
      ('La potion de fécondité II', 67, ${seasonMap['Livre III']}),
      ('La promesse', 22, ${seasonMap['Livre V']}),
      ('La quête des deux renards', NULL, ${seasonMap['Livre I']}),
      ('La queue du scorpion', 22, ${seasonMap['Livre I']}),
      ('La quinte juste', 55, ${seasonMap['Livre II']}),
      ('La réaffectation', NULL, ${seasonMap['Livre IV']}),
      ('La relève', NULL, ${seasonMap['Livre IV']}),
      ('La rémanence', 51, ${seasonMap['Livre IV']}),
      ('La rencontre', NULL, ${seasonMap['Livre II']}),
      ('La réponse', 49, ${seasonMap['Livre IV']}),
      ('La restriction', NULL, ${seasonMap['Livre II']}),
      ('La restriction II', 72, ${seasonMap['Livre III']}),
      ('La retraite', NULL, ${seasonMap['Livre I']}),
      ('La révolte', 23, ${seasonMap['Livre II']}),
      ('La révolte III', 31, ${seasonMap['Livre IV']}),
      ('La révoquée', 28, ${seasonMap['Livre IV']}),
      ('La roche et le fer', 12, ${seasonMap['Livre V']}),
      ('La romance de Lancelot', 37, ${seasonMap['Livre I']}),
      ('La ronde', 34, ${seasonMap['Livre II']}),
      ('La sorcière', 5, ${seasonMap['Livre V']}),
      ('La supplique', 30, ${seasonMap['Livre V']}),
      ('La table de Breccan', 3, ${seasonMap['Livre I']}),
      ('La tarte aux fraises', 4, ${seasonMap['Livre IV']}),
      ('La tarte aux myrtilles', 2, ${seasonMap['Livre I']}),
      ('La taxe militaire', 21, ${seasonMap['Livre I']}),
      ('La veillée', 87, ${seasonMap['Livre III']}),
      ('La visite d''Ygerne', 59, ${seasonMap['Livre I']}),
      ('La vraie nature du graal', NULL, ${seasonMap['Livre I']}),
      ('Lacrimosa', 95, ${seasonMap['Livre I']}),
      ('Lacrimosa', 8, ${seasonMap['Livre VI']}),
      ('Le banquet des chefs', 16, ${seasonMap['Livre I']}),
      ('Le cadeau', 46, ${seasonMap['Livre II']}),
      ('Le cas Yvain', 39, ${seasonMap['Livre I']}),
      ('Le chaudron rutilant', NULL, ${seasonMap['Livre I']}),
      ('Le chevalier errant', 1, ${seasonMap['Livre III']}),
      ('Le chevalier femme', 6, ${seasonMap['épisodes pilotes']}),
      ('Le choix de Gauvain', 78, ${seasonMap['Livre IV']}),
      ('Le code de chevalerie', NULL, ${seasonMap['Livre I']}),
      ('Le complot', NULL, ${seasonMap['Livre II']}),
      ('Le coup d''épée', NULL, ${seasonMap['Livre I']}),
      ('Le culte secret', NULL, ${seasonMap['Livre III']}),
      ('Le dernier empereur', 56, ${seasonMap['Livre I']}),
      ('Le dernier jour', 24, ${seasonMap['Livre V']}),
      ('Le dernier recours', 3, ${seasonMap['Livre V']}),
      ('Le déserteur', 7, ${seasonMap['Livre III']}),
      ('Le désordre et la nuit', 99, ${seasonMap['Livre IV']}),
      ('Le destitué', 42, ${seasonMap['Livre V']}),
      ('Le dialogue de paix', 3, ${seasonMap['Livre II']}),
      ('Le dialogue de paix II', 42, ${seasonMap['Livre III']}),
      ('Le discobole', NULL, ${seasonMap['Livre I']}),
      ('Le donneur', 60, ${seasonMap['Livre II']}),
      ('Le dragon des tunnels', 86, ${seasonMap['Livre I']}),
      ('Le duel', 1, ${seasonMap['épisodes pilotes']}),
      ('Le fléau de dieu', 5, ${seasonMap['Livre I']}),
      ('Le fléau de dieu II', NULL, ${seasonMap['Livre III']}),
      ('Le fléau de dieu II', 17, ${seasonMap['Livre III']}),
      ('Le forfait', 23, ${seasonMap['Livre V']}),
      ('Le garçon qui criait au loup', NULL, ${seasonMap['Livre V']}),
      ('Le grand départ', 39, ${seasonMap['Livre IV']}),
      ('Le guet', 40, ${seasonMap['Livre II']}),
      ('Le jeu de la guerre', 63, ${seasonMap['Livre IV']}),
      ('Le jeu du caillou', 60, ${seasonMap['Livre II']}),
      ('Le jour d''Alexandre', NULL, ${seasonMap['Livre III']}),
      ('Le jurisconsulte', 27, ${seasonMap['Livre V']}),
      ('Le labyrinthe', NULL, ${seasonMap['Livre I']}),
      ('Le larcin', 38, ${seasonMap['Livre II']}),
      ('Le législateur', NULL, ${seasonMap['Livre III']}),
      ('Le magnanime', NULL, ${seasonMap['Livre III']}),
      ('Le maître d''armes', 9, ${seasonMap['Livre I']}),
      ('Le mangonneau', NULL, ${seasonMap['Livre III']}),
      ('Le médiateur', 96, ${seasonMap['Livre III']}),
      ('Le message codé', NULL, ${seasonMap['Livre II']}),
      ('Le monde d''arthur', NULL, ${seasonMap['Livre II']}),
      ('Le oud II', 75, ${seasonMap['Livre IV']}),
      ('Le pain', NULL, ${seasonMap['Livre I']}),
      ('Le paladin', 70, ${seasonMap['Livre IV']}),
      ('Le passage secret', NULL, ${seasonMap['Livre II']}),
      ('Le pédagogue', 71, ${seasonMap['Livre II']}),
      ('Le périple', 8, ${seasonMap['Livre V']}),
      ('Le petit poucet', 47, ${seasonMap['Livre III']}),
      ('Le poème', NULL, ${seasonMap['Livre II']}),
      ('Le porte bonheur', NULL, ${seasonMap['Livre III']}),
      ('Le portrait', NULL, ${seasonMap['Livre II']}),
      ('Le privilégié', 12, ${seasonMap['Livre IV']}),
      ('Le problème du chou', 70, ${seasonMap['Livre I']}),
      ('Le prodige du fakir', 60, ${seasonMap['Livre I']}),
      ('Le professionnel', 23, ${seasonMap['Livre III']}),
      ('Le rapport', 32, ${seasonMap['Livre IV']}),
      ('Le rassemblement du corbeau', 4, ${seasonMap['Livre II']}),
      ('Le rassemblement du corbeau II', 38, ${seasonMap['Livre IV']}),
      ('Le rebelle', 85, ${seasonMap['Livre II']}),
      ('Le reclassement', 14, ${seasonMap['Livre II']}),
      ('Le refuge', 55, ${seasonMap['Livre IV']}),
      ('Le renfort magique', 4, ${seasonMap['Livre III']}),
      ('Le renoncement II', NULL, ${seasonMap['Livre IV']}),
      ('Le répurgateur', 9, ${seasonMap['épisodes pilotes']}),
      ('Le retour de judée', 27, ${seasonMap['Livre I']}),
      ('Le retour du roi', 49, ${seasonMap['Livre V']}),
      ('Le rêve d''Ygerne', 64, ${seasonMap['Livre IV']}),
      ('Le royaume sans tête', 5, ${seasonMap['Livre V']}),
      ('Le sacrifice', 25, ${seasonMap['Livre I']}),
      ('Le sanglier de cornouailles', NULL, ${seasonMap['Livre III']}),
      ('Le sauvetage', 98, ${seasonMap['Livre IV']}),
      ('Le secret d''Arthur', 62, ${seasonMap['Livre II']}),
      ('Le secret de Lancelot', 53, ${seasonMap['Livre I']}),
      ('Le signe', 17, ${seasonMap['Livre I']}),
      ('Le sixième sens', NULL, ${seasonMap['Livre I']}),
      ('Le sort perdu', NULL, ${seasonMap['Livre II']}),
      ('Le terroriste', NULL, ${seasonMap['Livre II']}),
      ('Le tourment', 98, ${seasonMap['Livre I']}),
      ('Le tourment II', NULL, ${seasonMap['Livre II']}),
      ('Le tourment III', 69, ${seasonMap['Livre III']}),
      ('Le traitre', NULL, ${seasonMap['Livre IV']}),
      ('Le trouble', NULL, ${seasonMap['Livre III']}),
      ('Le vice de forme', 91, ${seasonMap['Livre IV']}),
      ('Legenda', NULL, ${seasonMap['Livre III']}),
      ('Les affranchis', 38, ${seasonMap['Livre III']}),
      ('Les alchimistes', 2, ${seasonMap['Livre II']}),
      ('Les aquitains', 15, ${seasonMap['Livre V']}),
      ('Les biens nommés', NULL, ${seasonMap['Livre IV']}),
      ('Les bonnes', 30, ${seasonMap['Livre IV']}),
      ('Les chaperons', NULL, ${seasonMap['Livre IV']}),
      ('Les cheveux noirs', 46, ${seasonMap['Livre III']}),
      ('Les chiens de guerre', 49, ${seasonMap['Livre II']}),
      ('Les classes de Bohort', 14, ${seasonMap['Livre II']}),
      ('Les clous de la sainte croix', 39, ${seasonMap['Livre III']}),
      ('Les dauphins', 13, ${seasonMap['Livre V']}),
      ('Les défis de Merlin', 15, ${seasonMap['Livre I']}),
      ('Les défis de Merlin II', 96, ${seasonMap['Livre III']}),
      ('Les embusqués', 35, ${seasonMap['Livre V']}),
      ('Les envahisseurs', 44, ${seasonMap['Livre IV']}),
      ('Les esclaves', 88, ${seasonMap['Livre II']}),
      ('Les exilés', 17, ${seasonMap['Livre V']}),
      ('Les exploités', NULL, ${seasonMap['Livre II']}),
      ('Les exploités II', NULL, ${seasonMap['Livre IV']}),
      ('Les félicitations', 86, ${seasonMap['Livre II']}),
      ('Les fesses de Guenièvre', NULL, ${seasonMap['Livre I']}),
      ('Les festivités', NULL, ${seasonMap['Livre II']}),
      ('Les fruits d''hiver', 16, ${seasonMap['Livre V']}),
      ('Les liaisons dangereuses', 15, ${seasonMap['Livre IV']}),
      ('Les mauvaises graines', 29, ${seasonMap['Livre II']}),
      ('Les misanthropes', 21, ${seasonMap['Livre II']}),
      ('Les neiges éternelles', 66, ${seasonMap['Livre II']}),
      ('Les nocturnales', 19, ${seasonMap['Livre V']}),
      ('Les nouveaux clans', 4, ${seasonMap['Livre V']}),
      ('Les nouveaux frères', 50, ${seasonMap['Livre I']}),
      ('Les novices', 34, ${seasonMap['Livre IV']}),
      ('Les paris II', 53, ${seasonMap['Livre III']}),
      ('Les pionniers', 40, ${seasonMap['Livre V']}),
      ('Les pisteurs', NULL, ${seasonMap['Livre IV']}),
      ('Les plaques de dissimulation', 90, ${seasonMap['Livre IV']}),
      ('Les recruteurs', 10, ${seasonMap['Livre V']}),
      ('Les repentant', 1, ${seasonMap['Livre V']}),
      ('Les repentants', 1, ${seasonMap['Livre V']}),
      ('Les rivales', NULL, ${seasonMap['Livre V']}),
      ('Les suppléants', 24, ${seasonMap['Livre III']}),
      ('Les tourelles', NULL, ${seasonMap['Livre III']}),
      ('Les transhumants', 37, ${seasonMap['Livre V']}),
      ('Les tuteurs', 16, ${seasonMap['Livre II']}),
      ('Les voeux', 45, ${seasonMap['Livre II']}),
      ('Les volontaires II', NULL, ${seasonMap['Livre II']}),
      ('Loth et le graal', 67, ${seasonMap['Livre IV']}),
      ('Mater dixit', 69, ${seasonMap['Livre II']}),
      ('Merlin l''archaïque', 56, ${seasonMap['Livre II']}),
      ('Miles ignotus', 1, ${seasonMap['Livre VI']}),
      ('Mission', 65, ${seasonMap['Livre III']}),
      ('Monogame', 14, ${seasonMap['Livre I']}),
      ('Morituri', NULL, ${seasonMap['Livre III']}),
      ('Neiges éternelles', NULL, ${seasonMap['Livre II']}),
      ('Nuptiae', 6, ${seasonMap['Livre VI']}),
      ('O''brother', 41, ${seasonMap['Livre II']}),
      ('Patience dans la plaine', NULL, ${seasonMap['Livre I']}),
      ('Perceval de sinope', NULL, ${seasonMap['Livre V']}),
      ('Perceval et le contre-sirop', NULL, ${seasonMap['Livre II']}),
      ('Perceval fait raitournelle', NULL, ${seasonMap['Livre IV']}),
      ('Plus près de toi', 22, ${seasonMap['Livre II']}),
      ('Plusieurs épisodes de la saison V', NULL, ${seasonMap['Livre V']}),
      ('Poltergeist', NULL, ${seasonMap['Livre III']}),
      ('Polymorphie', NULL, ${seasonMap['Livre I']}),
      ('Praeceptores', 3, ${seasonMap['Livre VI']}),
      ('Promotion de la série', NULL, ${seasonMap['décembre 2004']}),
      ('Promotion de la série', NULL, ${seasonMap['janvier 2005']}),
      ('Raison d''argent II', 88, ${seasonMap['Livre III']}),
      ('Raisons et sentiments', 3, ${seasonMap['Livre IV']}),
      ('Réplique souvent répétée', NULL, ${seasonMap['Livre V']}),
      ('Saponides et détergents', 74, ${seasonMap['Livre III']}),
      ('Séfriane d''aquitaine', 16, ${seasonMap['Livre III']}),
      ('Seigneur Caïus', 22, ${seasonMap['Livre IV']}),
      ('Séli et les rongeurs', NULL, ${seasonMap['Livre II']}),
      ('Sept cent quarante-quatre', NULL, ${seasonMap['Livre II']}),
      ('Silbury hill', 5, ${seasonMap['Livre II']}),
      ('Sous les verrous', 24, ${seasonMap['Livre II']}),
      ('Spangenhelm', 1, ${seasonMap['Livre II']}),
      ('Spiritueux', 33, ${seasonMap['Livre II']}),
      ('Stargate', 93, ${seasonMap['Livre II']}),
      ('Tel un chevalier', NULL, ${seasonMap['Livre I']}),
      ('The game', NULL, ${seasonMap['Livre II']}),
      ('Tous les matins du monde', 2, ${seasonMap['Livre IV']}),
      ('Tous les matins du monde II', 2, ${seasonMap['Livre IV']}),
      ('Trois cent soixante degrés', 97, ${seasonMap['Livre II']}),
      ('Un bruit dans la nuit', 61, ${seasonMap['Livre I']}),
      ('Un roi à la taverne', 21, ${seasonMap['Livre I']}),
      ('Un roi à la taverne II', 26, ${seasonMap['Livre II']}),
      ('Unagi', NULL, ${seasonMap['Livre I']}),
      ('Unagi II', NULL, ${seasonMap['Livre II']}),
      ('Unagi IV', NULL, ${seasonMap['Livre IV']}),
      ('Unagi V', 39, ${seasonMap['Livre V']}),
      ('Vae soli !', 14, ${seasonMap['Livre V']}),
      ('Vox populi II', NULL, ${seasonMap['Livre II']}),
      ('Vox populi III', 58, ${seasonMap['Livre IV']}),
      ('Witness', 82, ${seasonMap['Livre III']})
      ON CONFLICT ("name", "number", "seasonId") DO NOTHING
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM "episode" 
      WHERE "seasonId" IN (
        SELECT s.id 
        FROM "season" s 
        INNER JOIN "show" sh ON s."showId" = sh.id 
        WHERE sh.name = 'kaamelott'
      )
    `);
  }
}
