import { MigrationInterface, QueryRunner } from 'typeorm';

export class SeedActor1754486179127 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      INSERT INTO "Actor" ("firstName", "lastName") VALUES 
      ('Alain', 'Chabat'),
      ('Alain', 'Chapuis'),
      ('Alexandra', 'Saadoun'),
      ('Alexandre', 'Astier'),
      ('Alexis', 'Hénon'),
      ('Anne', 'Benoît'),
      ('Anne', 'Girouard'),
      ('Anouk', 'Grinberg'),
      ('Antoine', 'de Caunes'),
      ('Audrey', 'Fleurot'),
      ('Aurélien', 'Portehaut'),
      ('Axelle', 'Laffont'),
      ('Bernard', 'Lecoq'),
      ('Brice', 'Fournier'),
      ('Bruno', 'Fontaine'),
      ('Bruno', 'Salomone'),
      ('Carlo', 'Brandt'),
      ('Caroline', 'Ferrus'),
      ('Caroline', 'Pascal'),
      ('Christian', 'Bujeau'),
      ('Christian', 'Clavier'),
      ('Claire', 'Nadeau'),
      ('Clovis', 'Cornillac'),
      ('Élie', 'Semoun'),
      ('Émilie', 'Dequenne'),
      ('Emmanuel', 'Meirieu'),
      ('Franck', 'Pitiot'),
      ('François', 'Levantal'),
      ('François', 'Morel'),
      ('François', 'Rollin'),
      ('Frank', 'Pitiot'),
      ('Georges', 'Beller'),
      ('Géraldine', 'Nakache'),
      ('Gilles', 'Graveleau'),
      ('Guillaume', 'Briat'),
      ('Guillaume', 'Gallienne'),
      ('Jacques', 'Chambon'),
      ('Jean-Marc', 'Avocat'),
      ('Jean-Christophe', 'Hembert'),
      ('Jean-Robert', 'Lombard'),
      ('Joëlle', 'Sevilla'),
      ('Josée', 'Drevon'),
      ('Lan', 'Truong'),
      ('Laurent', 'Gamelon'),
      ('Lionnel', 'Astier'),
      ('Loïc', 'Varraut'),
      ('Loránt', 'Deutsch'),
      ('Magali', 'Saadoun'),
      ('Manu', 'Payet'),
      ('Nicolas', 'Gabion'),
      ('Pascal', 'Demolon'),
      ('Pascal', 'Vincent'),
      ('Patrick', 'Chesnais'),
      ('Philippe', 'Nahon'),
      ('Pierre', 'Mondy'),
      ('Serge', 'Papagalli'),
      ('Simon', 'Astier'),
      ('Stéphane', 'Margot'),
      ('Sting', ''),
      ('Tcheky', 'Karyo'),
      ('Thibault', 'Roux'),
      ('Thomas', 'Cousseau'),
      ('Tony', 'Saba'),
      ('Valérie', 'Keruzoré'
      ('Vanessa', 'Guedj'
      ('Yvan', 'Le Bolloc''h'),
      ON CONFLICT DO NOTHING
    `);

    console.log('✅ Actor insérés avec succès');
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      DELETE FROM "Actor" WHERE ("firstName", "lastName") IN (
        ('Alain', 'Chabat'),
        ('Alain', 'Chapuis'),
        ('Alexandra', 'Saadoun'),
        ('Alexandre', 'Astier'),
        ('Alexis', 'Hénon'),
        ('Anne', 'Benoît'),
        ('Anne', 'Girouard'),
        ('Anouk', 'Grinberg'),
        ('Antoine', 'de Caunes'),
        ('Audrey', 'Fleurot'),
        ('Aurélien', 'Portehaut'),
        ('Axelle', 'Laffont'),
        ('Bernard', 'Lecoq'),
        ('Brice', 'Fournier'),
        ('Bruno', 'Fontaine'),
        ('Bruno', 'Salomone'),
        ('Carlo', 'Brandt'),
        ('Caroline', 'Ferrus'),
        ('Caroline', 'Pascal'),
        ('Christian', 'Bujeau'),
        ('Christian', 'Clavier'),
        ('Claire', 'Nadeau'),
        ('Clovis', 'Cornillac'),
        ('Élie', 'Semoun'),
        ('Émilie', 'Dequenne'),
        ('Emmanuel', 'Meirieu'),
        ('Franck', 'Pitiot'),
        ('François', 'Levantal'),
        ('François', 'Morel'),
        ('François', 'Rollin'),
        ('Frank', 'Pitiot'),
        ('Georges', 'Beller'),
        ('Géraldine', 'Nakache'),
        ('Gilles', 'Graveleau'),
        ('Guillaume', 'Briat'),
        ('Guillaume', 'Gallienne'),
        ('Jacques', 'Chambon'),
        ('Jean-Marc', 'Avocat'),
        ('Jean-Christophe', 'Hembert'),
        ('Jean-Robert', 'Lombard'),
        ('Joëlle', 'Sevilla'),
        ('Josée', 'Drevon'),
        ('Lan', 'Truong'),
        ('Laurent', 'Gamelon'),
        ('Lionnel', 'Astier'),
        ('Loïc', 'Varraut'),
        ('Loránt', 'Deutsch'),
        ('Magali', 'Saadoun'),
        ('Manu', 'Payet'),
        ('Nicolas', 'Gabion'),
        ('Pascal', 'Demolon'),
        ('Pascal', 'Vincent'),
        ('Patrick', 'Chesnais'),
        ('Philippe', 'Nahon'),
        ('Pierre', 'Mondy'),
        ('Serge', 'Papagalli'),
        ('Simon', 'Astier'),
        ('Stéphane', 'Margot'),
        ('Sting', ''),
        ('Tcheky', 'Karyo'),
        ('Thibault', 'Roux'),
        ('Thomas', 'Cousseau'),
        ('Tony', 'Saba'),
        ('Valérie', 'Keruzoré'
        ('Vanessa', 'Guedj'
        ('Yvan', 'Le Bolloc''h'),
      )
    `);

    console.log('🗑️ Actor supprimés');
  }
}
